### PR TITLE
Update demo app with SDK V2

### PR DESCRIPTION
**Pull request by benjaminvolland**
implement new Teads SDK v2

### CODE REVIEW

**Comment by HugoGresse** [comment]
retest

**Comment by HugoGresse** [comment]
tetest

**Comment by HugoGresse** [comment]
retest

**Comment by HugoGresse** [comment]
retest

**Comment by HugoGresse** [comment]
retest

**Comment by HugoGresse** [comment]
retest

**Comment by HugoGresse** [comment]
retest

**Comment by HugoGresse** [comment]
retest

**Comment by benjaminvolland** [comment]
retest

**Comment by benjaminvolland** [comment]
retest

**Pull request closed without merging**
