### PR TITLE
Update Teads SDK to 2.2.6

### PR DESCRIPTION
**Pull request by benjaminvolland**
- Add Engage format
- Remove Interstitial format
- minor bug fix

### CODE REVIEW

**Comment by HugoGresse** [comment]
restest

**Comment by HugoGresse** [comment]
retest

**Comment by benjaminvolland** [comment]
retest

**Comment by HugoGresse** [comment]
retest

**Comment by HugoGresse** [comment]
retest

**Comment by HugoGresse** [comment]
retest

**Comment by HugoGresse** [comment]
retest

**Pull request merged**
